name = "zeiterfassung"
main = "worker/index.ts"
compatibility_date = "2026-05-31"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true
